// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHA79ihAnXOO7sJBzNqCyOmZPHeKhrtpQ',
    appId: '1:418457317725:web:b65735ff21d5df230178b4',
    messagingSenderId: '418457317725',
    projectId: 'chatapp-5e7e9',
    authDomain: 'chatapp-5e7e9.firebaseapp.com',
    storageBucket: 'chatapp-5e7e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eGdpEukJkHrItNkrK3ddeWyXxhYR5B0',
    appId: '1:418457317725:android:edced55b66617be40178b4',
    messagingSenderId: '418457317725',
    projectId: 'chatapp-5e7e9',
    storageBucket: 'chatapp-5e7e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Mz99G_gk6PeGFx_lAjgqJnrr-DL7Dq8',
    appId: '1:418457317725:ios:e7484aeb726368df0178b4',
    messagingSenderId: '418457317725',
    projectId: 'chatapp-5e7e9',
    storageBucket: 'chatapp-5e7e9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Mz99G_gk6PeGFx_lAjgqJnrr-DL7Dq8',
    appId: '1:418457317725:ios:e7484aeb726368df0178b4',
    messagingSenderId: '418457317725',
    projectId: 'chatapp-5e7e9',
    storageBucket: 'chatapp-5e7e9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHA79ihAnXOO7sJBzNqCyOmZPHeKhrtpQ',
    appId: '1:418457317725:web:88f0d74ac75289ec0178b4',
    messagingSenderId: '418457317725',
    projectId: 'chatapp-5e7e9',
    authDomain: 'chatapp-5e7e9.firebaseapp.com',
    storageBucket: 'chatapp-5e7e9.appspot.com',
  );
}
